//
// Created by facundo on 2/9/26.
//

#ifndef ALGORITMOS_Y_ESTRUCTURAS_DE_DATOS_GUARDSQUADMEMBER_H
#define ALGORITMOS_Y_ESTRUCTURAS_DE_DATOS_GUARDSQUADMEMBER_H

class GuardSquadMember
{
};

#endif // ALGORITMOS_Y_ESTRUCTURAS_DE_DATOS_GUARDSQUADMEMBER_H
