# Wires clang-tidy into a target's build when CYBERCBA_ENABLE_CLANG_TIDY is enabled.
function(cybercba_enable_clang_tidy target)
    if(CYBERCBA_ENABLE_CLANG_TIDY)
        find_program(CLANG_TIDY_EXE NAMES clang-tidy)
        if(CLANG_TIDY_EXE)
            set_target_properties(${target} PROPERTIES CXX_CLANG_TIDY "${CLANG_TIDY_EXE}")
        else()
            message(WARNING "clang-tidy requested but not found; skipping for ${target}")
        endif()
    endif()
endfunction()
